[include]
autoload = false
files = ["profile_a/"]

[accessibility]
ui_scale = 1.0

[system.monitor]
gpu_poll_seconds = 2

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

[theme.templates]
builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "kitty", "qt", "alacritty" ]
